### ISSUE TITLE
Add (level 2) "read_status" to all records

### ISSUE THREAD

**Issue by agstephens** [cedadev/ceda-fbs#15]

**Comment by rsmith013** [comment]
Needed to add to:
- metadata_tags

Already running correctly for:
- netcdf
- nasa ames
- pp
- grib

Not required for following handlers as these files do not return at level2:
- esasafe
- hdf
- generic 
- kmz

Will need to add read status to level 3 for:
- esasafe
- hdf
- kmz

**Comment by rsmith013** [comment]
This only adds one more file on to of what was there before. The rest of the files are  not opened to extract phenomena and so they have no read status.
