### ISSUE TITLE
Add path analyser to "directory" field

### ISSUE THREAD

**Issue by agstephens** [cedadev/ceda-fbs#16]
Need to be able to query the directory with following matches:
 - match exactly
 - match any path that begins with given directory string ("begins with")
 - match any path that contains the given directory string ("contains")

**Comment by rsmith013** [comment]
I don't think we need to modify the index to achieve this, just the query.

- match exactly

```
POST ceda-level2-2018-01-14/_search
{
  "query": {
    "match": {
      "info.directory": "/badc/cmip5/data/cmip5/output1/BCC/bcc-csm1-1/noVolc1960"
    }
  }
}
```
- match any path that begins with given dir

```
POST ceda-level2-2018-01-14/_search
{
  "query": {
    "match_phrase_prefix": {
      "info.directory.analyzed": "/badc/specs/data/SPECS/output/KNMI/EC-EARTH2/seaIceInit/S19471101/day/atmos/day/tasmax/"
    }
  }
}

```

- match any path that contains given dir string

```
POST ceda-level2-2018-01-14/_search
{
  "query": {
    "match_phrase": {
      "info.directory.analyzed": "data/cmip5/output1/BCC"
    }
  }
}
```
