### ISSUE TITLE
Create query for Level 2 that resolve path to aggregation of phenomena

### ISSUE THREAD

**Issue by agstephens** [cedadev/ceda-fbs#18]
Input will be a file path.

Output will be a single list of dictionaries containing the complete phenomena objects (maybe nested).

**Comment by rsmith013** [comment]
Once the index has rescanned should be able to do this to return list of phenomena under a specified file path. The output will need parsing but should be simple enough.
key:value pairs are "," delimited
names are ";" delimited to give a clear distinction.
```
{
  "query":{
    "match_phrase_prefix": {
      "info.directory.analyzed": "/badc/cmip5/data/cmip5/output1/NIMR-KMA/"
    }
  },
  "aggs":{
    "phenom": {
      "terms": {
        "field": "info.phenomena.agg_string",
        "size": 1000
      }
    }
  },
  "size": 0
}
```
