### ISSUE TITLE
Reinstate badc CSV file handler and regex

### ISSUE THREAD

**Issue by agstephens** [cedadev/ceda-fbs#22]
Discuss with Sam and Graham some good examples of this format in the archive.

**Comment by gap736uk** [comment]
@rsmith013 in the BADC-CSV format you just need to scrape those lines starting with:

`long_name`
or 
`standard_name`
these then break down into the following components:

## long_name
examples:
long_name,1, Surface air temperature at 2m, C
long_name,temp, Surface air temperature at 2m, C

<attribute>,<column-ref>,<long-name string>, <units>

breaks down into these parts:
long_name - this is just the attribute field name
1 or temp - this is the column reference and becomes your "var_id" for scraping purposes, though as you'll appreciate if it's just a number this is useless!
Surface air temperature at 2m - this is the long-name you'll want to scrape. It follows csv encoding rules so could be enclosed with speech marks if there's a need to have a comma in this string etc.
C - this is the units

### standard_name
examples
standard_name,1, air_temperature, C
standard_name,temp, air_temperature, C

As above, but giving the CF-Conventions for the variable.

### linking it all together
essentially just use the second value as your "var_id" as you would in netCDFs. It's a column reference that tells you how to link the metadata together and which column of data to which it applies.

Parse all the content using a CSV parser

**Comment by agstephens** [comment]
@gap736uk, is there not a library for reading BADC CSV?

**Comment by rsmith013** [comment]
reinstated with fcdbf7c4a1a5587f9e69df3c2090d33667945473
