### ISSUE TITLE
Rewrite phenoma() method for all file format handlers

### ISSUE THREAD

**Issue by agstephens** [cedadev/ceda-fbs#23]
We want the response to be a list of dictionaries, e.g.:

```
[ 
{'var_id': 't', 'long_name': 'Temp', 'units': 'K'},
{'name': 'Specific humidity'}
]
```

**Comment by agstephens** [comment]
Then we need to derive a `best_name` field by choosing in the following order:

1. long_name
2. standard_name
3. title
4. name
5. short_name
6. var_id
7. *Should never get here*

**Comment by gap736uk** [comment]
@agstephens  - I bet you do end up with reaching number 6 with entries as useful as a chocolate tea-pot, such as "var1"..... and there's nowt much else of use in the file. (sadly this may become increasingly likely with the move to accept just "reference-only" datasets where we take data just as given by the user and will be accepting such items into the archive!
