### ISSUE TITLE
MST radar v4 files not scanned

### ISSUE THREAD

**Issue by gap736uk** [cedadev/ceda-fbs#29]
MST radar data are one of the best examples of CF compliant netCDF files that you'll find around...

...yet there appears to have been an error trying to scan these files to extract the parameters from them, which is unfortunate as these are high profile data within the NCAS community.

The version 3 data scanned OK.

Please could we check why these files failed to be scanned and see if we can get the parameter info into 

To see the issue I did this:

`GET ceda-level-2/_search
{
  "query": {
    "match_phrase_prefix": {
      "info.directory.analyzed": "/badc/mst/data/nerc-mstrf"
    }
  }
}`

which yield returns like:

`{
        "_index": "ceda-level2-2018-02-20",
        "_type": "file",
        "_id": "9af708c4e324ce46ec73aabf401e6ea2c05480a6",
        "_score": 18.640104,
        "_source": {
          "info": {
            "name": "nerc-mstrf-radar-mst_capel-dewi_20150910_st300_cardinal_33min-smoothing_v4-0.nc",
            "format": "NetCDF",
            "read_status": "Read Error",
            "directory": "/badc/mst/data/nerc-mstrf-radar-mst/v4-0/st-mode/cardinal/2015/09",
            "location": "on_disk",
            "name_auto": "nerc-mstrf-radar-mst_capel-dewi_20150910_st300_cardinal_33min-smoothing_v4-0.nc",
            "md5": "",
            "type": ".nc",
            "size": 1.325
          }
        }
      },`

**Comment by rsmith013** [comment]
OK. I have tracked the issue down to the use of a degrees symbol in the file u'\xb0'. This is throwing an error when translating to ascii. I'll have a look to see what we can do to get round that.

**Comment by agstephens** [comment]
@rsmith013: we should try to use unicode for everything nowadays (if not too hard).

**Comment by rsmith013** [comment]
I am afraid I have pushed the ball back to you @gap736uk. The handler now reads the file and encodes the characters properly but that means you'll have a \u00b0 to deal with at the other end.

**Comment by gap736uk** [comment]
@agstephens  - the next step is to figure out why these aren't getting into MOLES...

**Comment by rsmith013** [comment]
Work is complete from FBS side of things.

**Comment by gap736uk** [comment]
I'm going to make a new ticket in MOLES Git project
