### ISSUE TITLE
MD5 scanning - need to work out best method

### ISSUE THREAD

**Issue by agstephens** [cedadev/ceda-fbs#3]
Maybe create script to query ES then update records with MD5. (would mean separate code base / run-location).

**Comment by agstephens** [comment]
Ag sent some code in Slack. Key issues:

 - MD5s already exist in logs (in checkm format - I think).
 - We can mine them and inject values into Level 1 of FBS.

We have two options:
 1. ceda-fbs talks to md5 archive when scanning.

OR

2. Separate process updates each ES record with md5.

**Comment by rsmith013** [comment]
This has also been moved to https://github.com/cedadev/ceda-elasticsearch-tools
however it has been decided to run this as a tool once an index has been created. 
Step 1: Extract as many MD5s as possible from the logs
Step 2: Calculate any remaining file MD5s and inject into ES
